C3_jammy_task:
  timeout_in: 120m
  container:
    dockerfile: tools/install/jammy/Dockerfile
    cpu: 8
    memory: 24
  test_script:
    - export CC=clang-12
    - export CXX=clang++-12
    - bazel build
      --define=WITH_GUROBI=OFF
      --local_resources=ram=24000
      --local_resources=cpu=8
      --jobs=8 
      //...
    - bazel test
      --define=WITH_GUROBI=OFF
      --local_resources=ram=24000
      --local_resources=cpu=8
      //...
C3_noble_task:
  timeout_in: 120m
  container:
    dockerfile: tools/install/noble/Dockerfile
    cpu: 8
    memory: 24
  test_script:
    - export CC=clang-12
    - export CXX=clang++-12
    - bazel build
      --define=WITH_GUROBI=OFF
      --local_resources=ram=24000
      --local_resources=cpu=8
      --jobs=8 
      //...
    - bazel test
      --define=WITH_GUROBI=OFF
      --local_resources=ram=24000
      --local_resources=cpu=8
      //...