registry_config: ENCRYPTED[!88cf0d757d2f8b93dca9e57dc166b65ddedef6378e7ac12a91a022ab3fb28dd47b10d452dc5c53a68e144e6bdbae999b!]
jammy_task:
  timeout_in: 120m
  container:
    image: ghcr.io/dairlab/docker-dair/jammy-dair-base:v1.42
    cpu: 8
    memory: 24
  test_script:
    - export CC=clang-15
    - export CXX=clang++-15
    - bazel build
      --local_resources=ram=24000
      --local_resources=cpu=8
      --jobs=8
      --remote_cache=http://$CIRRUS_HTTP_CACHE_HOST
      //...
    - apt update && apt install -y lcov
    # Coverage will run tests, as well as coverage for the code.
    - bazel coverage
      --combined_report=lcov
      --local_resources=ram=24000
      --local_resources=cpu=8
      --remote_cache=http://$CIRRUS_HTTP_CACHE_HOST
      //...
    # - genhtml --branch-coverage
    #   --output genhtml
    #   "$(bazel info output_path)/_coverage/_coverage_report.dat"
  format_script:
    - find . 
      -name "*.cc" -o -name "*.h" -o -name "*.hpp" | 
      xargs clang-format --dry-run --Werror 
      --output-replacements-xml > replacements.xml  2>&1
  always:
    jammy_test_artifacts:
      path: "bazel-testlogs/**/test.xml"
      format: junit
    jammy_coverage_artifacts:
      path: "genhtml/index.html"
      type: text/html
    jammy_format_artifacts:
      path: "replacements.xml"
      type: text/xml

noble_task:
  timeout_in: 120m
  container:
    image: ghcr.io/dairlab/docker-dair/noble-dair-base:v1.42
    cpu: 8
    memory: 24
  test_script:
    - export CC=clang-15
    - export CXX=clang++-15
    - bazel build
      --local_resources=ram=24000
      --local_resources=cpu=8
      --jobs=8
      --remote_cache=http://$CIRRUS_HTTP_CACHE_HOST
      //...
    - apt update && apt install -y lcov
    # Coverage will run tests, as well as coverage for the code.
    - bazel coverage
      --combined_report=lcov
      --local_resources=ram=24000
      --local_resources=cpu=8
      --remote_cache=http://$CIRRUS_HTTP_CACHE_HOST
      //...
    # - genhtml --branch-coverage
    #   --output genhtml
    #   "bazel-out/_coverage/_coverage_report.dat"
  format_script:
    - find . 
      -name "*.cc" -o -name "*.h" -o -name "*.hpp" | 
      xargs clang-format --dry-run --Werror 
      --output-replacements-xml > replacements.xml  2>&1
  always:
    noble_test_artifacts:
      path: "bazel-testlogs/**/test.xml"
      format: junit
    noble_coverage_artifacts:
      path: "genhtml/index.html"
      type: text/html
    noble_format_artifacts:
      path: "replacements.xml"
      type: text/xml
