registry_config: ENCRYPTED[!88cf0d757d2f8b93dca9e57dc166b65ddedef6378e7ac12a91a022ab3fb28dd47b10d452dc5c53a68e144e6bdbae999b!]
jammy_task:
  timeout_in: 120m
  container:
    image: ghcr.io/dairlab/docker-dair/jammy-dair-base:v1.42
    cpu: 8
    memory: 24
  format_script:
    - apt update && apt install -y clang-format
    - ./tools/scripts/check_format.sh
  test_script:
    - export CC=clang-15
    - export CXX=clang++-15
    - bazel build
      --local_resources=ram=24000
      --local_resources=cpu=8
      --jobs=8
      --remote_cache=http://$CIRRUS_HTTP_CACHE_HOST
      //...
    - bazel test
      --local_resources=ram=24000
      --local_resources=cpu=8
      --jobs=8
      --test_output=all
      --remote_cache=http://$CIRRUS_HTTP_CACHE_HOST
      //...
  jammy_test_artifacts:
    path: "bazel-testlogs/**/test.xml"
    format: junit
  coverage_script:
    - apt update && apt install -y lcov
    - bazel coverage
      --combined_report=lcov
      --local_resources=ram=24000
      --local_resources=cpu=8
      --remote_cache=http://$CIRRUS_HTTP_CACHE_HOST
      --remote_download_minimal
      --strategy=CoverageReport=local
      --experimental_fetch_all_coverage_outputs
      //...
    - genhtml --branch-coverage
      --output coverage_report
      "bazel-out/_coverage/_coverage_report.dat"
  jammy_coverage_artifacts:
    path: "coverage_report/**/*"
    type: text/html

noble_task:
  timeout_in: 120m
  container:
    image: ghcr.io/dairlab/docker-dair/noble-dair-base:v1.42
    cpu: 8
    memory: 24
  format_script:
    - apt update && apt install -y clang-format
    - ./tools/scripts/check_format.sh
  test_script:
    - export CC=clang-15
    - export CXX=clang++-15
    - bazel build
      --local_resources=ram=24000
      --local_resources=cpu=8
      --jobs=8
      --remote_cache=http://$CIRRUS_HTTP_CACHE_HOST
      //...
    - bazel test
      --local_resources=ram=24000
      --local_resources=cpu=8
      --jobs=8
      --test_output=all
      --remote_cache=http://$CIRRUS_HTTP_CACHE_HOST
      //...
  noble_test_artifacts:
    path: "bazel-testlogs/**/test.xml"
    format: junit
  coverage_script:
    - apt update && apt install -y lcov
    - bazel coverage
      --combined_report=lcov
      --local_resources=ram=24000
      --local_resources=cpu=8
      --remote_cache=http://$CIRRUS_HTTP_CACHE_HOST
      --remote_download_minimal
      --strategy=CoverageReport=local
      --experimental_fetch_all_coverage_outputs
      //...
    - genhtml --branch-coverage
      --output coverage_report
      "bazel-out/_coverage/_coverage_report.dat"
  noble_coverage_artifacts:
    path: "coverage_report/**/*"
    type: text/html
