# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'debug.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.spinStart = QtWidgets.QSpinBox(self.centralwidget)
        self.spinStart.setObjectName("spinStart")
        self.verticalLayout.addWidget(self.spinStart)
        self.spinEnd = QtWidgets.QSpinBox(self.centralwidget)
        self.spinEnd.setObjectName("spinEnd")
        self.verticalLayout.addWidget(self.spinEnd)
        self.comboDimension = QtWidgets.QComboBox(self.centralwidget)
        self.comboDimension.setObjectName("comboDimension")
        self.comboDimension.addItem("")
        self.comboDimension.addItem("")
        self.comboDimension.addItem("")
        self.verticalLayout.addWidget(self.comboDimension)
        self.pushButtonPlot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPlot.setObjectName("pushButtonPlot")
        self.verticalLayout.addWidget(self.pushButtonPlot)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboDimension.setItemText(0, _translate("MainWindow", "0: N"))
        self.comboDimension.setItemText(1, _translate("MainWindow", "1: M"))
        self.comboDimension.setItemText(2, _translate("MainWindow", "2: H"))
        self.pushButtonPlot.setText(_translate("MainWindow", "PushButton"))
